---
# tasks file for rpireporter
- apt: 
    name: 
      - git 
      - python3 
      - python3-pip 
      - python3-tzlocal 
      - python3-sdnotify 
      - python3-colorama 
    state: latest
    update_cache: yes
  
- git:
    repo: https://github.com/ironsheep/RPi-Reporter-MQTT2HA-Daemon.git
    dest: /opt/RPi-Reporter-MQTT2HA-Daemon
    clone: yes
    force: yes

- pip:
    requirements: /opt/RPi-Reporter-MQTT2HA-Daemon/requirements.txt

- template:
    src: config.ini.j2
    dest: /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini

#Configure Rpi Reporter to run as a Daemon
- name: Add user "daemon" to "video" grups
  user:
    name: daemon
    groups: video
    append: true

- name: Create a symbolic link
  file:
    src: /opt/RPi-Reporter-MQTT2HA-Daemon/isp-rpi-reporter.service
    dest: /etc/systemd/system/isp-rpi-reporter.service
    state: link

- name: Start isp-rpi-reporter.service service
  systemd:
    name: isp-rpi-reporter.service
    state: restarted
    enabled: yes
    daemon-reload: yes